apiVersion: v1
kind: Service
metadata:
  name: nombre-del-servicio
spec:
  selector:
    app: nombre-del-pod
  ports:
    - protocol: Protocolo-del-puerto (por ejemplo, TCP)
      port: Puerto-del-servicio
      targetPort: Puerto-del-contenedor



apiVersion: La versión de la API de Kubernetes que estás utilizando.
kind: El tipo de recurso, que en este caso es un servicio.
metadata: Información sobre el servicio, como el nombre.
spec: La especificación del servicio.
selector: Los pods que este servicio va a exponer. En este caso, "app" es la etiqueta y
          "nombre-del-pod" es el valor de esa etiqueta que deben tener los pods para ser seleccionados.
ports: La configuración de los puertos para el servicio.
protocol: El protocolo del puerto, como TCP o UDP.
port: El puerto expuesto en el servicio.
targetPort: El puerto al que se redirige el tráfico dentro de los pods seleccionados.